using BasketApp.Domain.Entities;
using BasketApp.Infrastructure.Persistence;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BasketApp.Infrastructure.Seeders
{
    public class PlayerSeeder
    {

        private readonly BasketAppDbContext _dbContext;
        public PlayerSeeder(BasketAppDbContext dbContext)
        {

            _dbContext = dbContext;
        }

        public async Task Seed()
        {
            if (await _dbContext.Database.CanConnectAsync())
            {
                if (!_dbContext.Players.Any())
                {
                    var playersData = new List<Player>
                    {
                        new Player { Name = "Jayson Tatum", TeamID = 8, Age = 25, Height = "6-8", Position = "F-G"  },
                        new Player { Name = "Jrue Holiday", TeamID = 8, Age = 33, Height = "6-4", Position = "G" },
                        new Player { Name = "Jaylen Brown", TeamID = 8, Age = 27, Height = "6-6", Position = "G-F"  },
                        new Player { Name = "Kristaps Porzingis", TeamID = 8, Age = 28, Height = "7-2", Position = "F-C" },
                        new Player { Name = "Derrick White", TeamID = 8, Age = 29, Height = "6-4", Position = "G"  },
                        new Player { Name = "Payton Pritchard", TeamID = 8, Age = 25, Height = "6-1", Position = "G" },
                        new Player { Name = "Al Horford", TeamID = 8, Age = 37, Height = "6-9", Position = "C-F"  },
                        new Player { Name = "Nathan Knight", TeamID = 8, Age = 26, Height = "6-8", Position = "F-C" },
                        new Player { Name = "Sam Hauser", TeamID = 8, Age = 25, Height = "6-7", Position = "F"  },
                        new Player { Name = "Luke Kornet", TeamID = 8, Age = 28, Height = "7-1", Position = "C-F" },
                        new Player { Name = "Lamar Stevens", TeamID = 8, Age = 26, Height = "6-7", Position = "F"  },
                        new Player { Name = "Dariq Whitehead", TeamID = 35, Age = 25, Height = "6-8", Position = "F-G" },
                        new Player { Name = "Royce O'Neale", TeamID = 35, Age = 30, Height = "6-6", Position = "F" },
                        new Player { Name = "Dariq Whitehead", TeamID = 35, Age = 19, Height = "6-6", Position = "F" },
                        new Player { Name = "Mikal Bridges", TeamID = 35, Age = 27, Height = "6-6", Position = "G-F" },
                        new Player { Name = "Cameron Johnson", TeamID = 35, Age = 27, Height = "6-8", Position = "F" },
                        new Player { Name = "Dennis Smith Jr.", TeamID = 35, Age = 26, Height = "6-3", Position = "G" },
                        new Player { Name = "Lonnie Walker IV", TeamID = 35, Age = 24, Height = "6-4", Position = "G-F" },
                        new Player { Name = "Trendon Watford", TeamID = 35, Age = 23, Height = "6-8", Position = "F" },
                        new Player { Name = "Ben Simmons", TeamID = 35, Age = 27, Height = "6-10", Position = "G-F" },
                        new Player { Name = "Armoni Brooks", TeamID = 35, Age = 25, Height = "6-3", Position = "G" },
                        new Player { Name = "Harry Giles III", TeamID = 35, Age = 25, Height = "6-10", Position = "F-C" },
                        new Player { Name = "Day'Ron Sharpe", TeamID = 35, Age = 22, Height = "6-9", Position = "C" },
                        new Player { Name = "Noah Clowney", TeamID = 35, Age = 19, Height = "6-9", Position = "F" },
                        new Player { Name = "Jalen Wilson", TeamID = 35, Age = 23, Height = "6-6", Position = "F" },
                        new Player { Name = "Cam Thomas", TeamID = 35, Age = 22, Height = "6-3", Position = "G" },
                        new Player { Name = "Spencer Dinwiddie", TeamID = 35, Age = 30, Height = "6-5", Position = "G" },
                        new Player { Name = "Dorian Finney-Smith", TeamID = 35, Age = 30, Height = "6-7", Position = "F" },
                        new Player { Name = "Nic Claxton", TeamID = 35, Age = 24, Height = "6-11", Position = "C" },
                        new Player { Name = "Keon Johnson", TeamID = 35, Age = 21, Height = "6-5", Position = "G" },
                        new Player { Name = "Jaylen Martin", TeamID = 7, Age = 19, Height = "6-6", Position = "G" },
                        new Player { Name = "Donte DiVincenzo", TeamID = 7, Age = 26, Height = "6-4", Position = "G" },
                        new Player { Name = "Jacob Toppin", TeamID = 7, Age = 23, Height = "6-8", Position = "F" },
                        new Player { Name = "Miles McBride", TeamID = 7, Age = 23, Height = "6-1", Position = "G" },
                        new Player { Name = "Josh Hart", TeamID = 7, Age = 28, Height = "6-4", Position = "G" },
                        new Player { Name = "Immanuel Quickley", TeamID = 7, Age = 24, Height = "6-2", Position = "G" },
                        new Player { Name = "Quentin Grimes", TeamID = 7, Age = 23, Height = "6-5", Position = "G" },
                        new Player { Name = "DaQuan Jeffries", TeamID = 7, Age = 26, Height = "6-5", Position = "G-F" },
                        new Player { Name = "RJ Barrett", TeamID = 7, Age = 23, Height = "6-6", Position = "F-G" },
                        new Player { Name = "Jalen Brunson", TeamID = 7, Age = 27, Height = "6-2", Position = "G" },
                        new Player { Name = "Evan Fournier", TeamID = 7, Age = 31, Height = "6-6", Position = "G-F" },
                        new Player { Name = "Charlie Brown Jr.", TeamID = 7, Age = 26, Height = "6-6", Position = "G" },
                        new Player { Name = "Dylan Windler", TeamID = 7, Age = 27, Height = "6-7", Position = "G-F" },
                        new Player { Name = "Mitchell Robinson", TeamID = 7, Age = 25, Height = "7-0", Position = "C-F" },
                        new Player { Name = "Julius Randle", TeamID = 7, Age = 29, Height = "6-8", Position = "F-C" },
                        new Player { Name = "Jericho Sims", TeamID = 7, Age = 25, Height = "6-10", Position = "C" },
                        new Player { Name = "Ryan Arcidiacono", TeamID = 7, Age = 29, Height = "6-3", Position = "G" },
                        new Player { Name = "Isaiah Hartenstein", TeamID = 7, Age = 25, Height = "7-0", Position = "C-F" },
                        new Player { Name = "Tyrese Maxey", TeamID = 9, Age = 23, Height = "6-2", Position = "G" },
                        new Player { Name = "KJ Martin", TeamID = 9, Age = 22, Height = "6-6", Position = "F" },
                        new Player { Name = "Marcus Morris Sr.", TeamID = 9, Age = 34, Height = "6-8", Position = "F" },
                        new Player { Name = "Mo Bamba", TeamID = 9, Age = 25, Height = "7-0", Position = "C" },
                        new Player { Name = "De'Anthony Melton", TeamID = 9, Age = 25, Height = "6-3", Position = "G" },
                        new Player { Name = "Kelly Oubre Jr.", TeamID = 9, Age = 27, Height = "6-7", Position = "F-G" },
                        new Player { Name = "Jaden Springer", TeamID = 9, Age = 21, Height = "6-4", Position = "G" },
                        new Player { Name = "Tobias Harris", TeamID = 9, Age = 31, Height = "6-8", Position = "F" },
                        new Player { Name = "Ricky Council IV", TeamID = 9, Age = 22, Height = "6-6", Position = "G" },
                        new Player { Name = "Joel Embiid", TeamID = 9, Age = 29, Height = "7-0", Position = "C-F" },
                        new Player { Name = "Patrick Beverley", TeamID = 9, Age = 35, Height = "6-2", Position = "G" },
                        new Player { Name = "Terquavion Smith", TeamID = 9, Age = 20, Height = "6-4", Position = "G" },
                        new Player { Name = "Danuel House Jr.", TeamID = 9, Age = 30, Height = "6-6", Position = "F-G" },
                        new Player { Name = "Furkan Korkmaz", TeamID = 9, Age = 26, Height = "6-7", Position = "G-F" },
                        new Player { Name = "Robert Covington", TeamID = 9, Age = 32, Height = "6-7", Position = "F" },
                        new Player { Name = "Javonte Smart", TeamID = 9, Age = 24, Height = "6-4", Position = "G" },
                        new Player { Name = "Nicolas Batum", TeamID = 9, Age = 34, Height = "6-8", Position = "G-F" },
                        new Player { Name = "Paul Reed", TeamID = 9, Age = 24, Height = "6-9", Position = "F" },
                        new Player { Name = "Javon Freeman-Liberty", TeamID = 10, Age = 24, Height = "6-3", Position = "G" },
                        new Player { Name = "Gradey Dick", TeamID = 10, Age = 20, Height = "6-6", Position = "G-F" },
                        new Player { Name = "Jalen McDaniels", TeamID = 10, Age = 25, Height = "6-9", Position = "F" },
                        new Player { Name = "OG Anunoby", TeamID = 10, Age = 26, Height = "6-7", Position = "F-G" },
                        new Player { Name = "Scottie Barnes", TeamID = 10, Age = 22, Height = "6-7", Position = "F-G" },
                        new Player { Name = "Precious Achiuwa", TeamID = 10, Age = 24, Height = "6-8", Position = "F" },
                        new Player { Name = "Ron Harper Jr.", TeamID = 10, Age = 23, Height = "6-4", Position = "G-F" },
                        new Player { Name = "Garrett Temple", TeamID = 10, Age = 37, Height = "6-5", Position = "G-F" },
                        new Player { Name = "Dennis Schroder", TeamID = 10, Age = 30, Height = "6-1", Position = "G" },
                        new Player { Name = "Jakob Poeltl", TeamID = 10, Age = 28, Height = "7-0", Position = "C" },
                        new Player { Name = "Thaddeus Young", TeamID = 10, Age = 35, Height = "6-8", Position = "F" },
                        new Player { Name = "Malachi Flynn", TeamID = 10, Age = 25, Height = "6-1", Position = "G" },
                        new Player { Name = "Markquis Nowell", TeamID = 10, Age = 23, Height = "5-7", Position = "G" },
                        new Player { Name = "Chris Boucher", TeamID = 10, Age = 30, Height = "6-9", Position = "F" },
                        new Player { Name = "Otto Porter Jr.", TeamID = 10, Age = 30, Height = "6-8", Position = "F" },
                        new Player { Name = "Gary Trent Jr.", TeamID = 10, Age = 24, Height = "6-5", Position = "G" },
                        new Player { Name = "Christian Koloko", TeamID = 10, Age = 23, Height = "7-0", Position = "C" },
                        new Player { Name = "Pascal Siakam", TeamID = 10, Age = 29, Height = "6-8", Position = "F" },
                        new Player { Name = "Coby White", TeamID = 11, Age = 23, Height = "6-5", Position = "G" },
                        new Player { Name = "Lonzo Ball", TeamID = 11, Age = 26, Height = "6-6", Position = "G" },
                        new Player { Name = "Andre Drummond", TeamID = 11, Age = 30, Height = "6-11", Position = "C" },
                        new Player { Name = "Jevon Carter", TeamID = 11, Age = 28, Height = "6-1", Position = "G" },
                        new Player { Name = "Alex Caruso", TeamID = 11, Age = 29, Height = "6-5", Position = "G" },
                        new Player { Name = "Zach LaVine", TeamID = 11, Age = 28, Height = "6-5", Position = "G" },
                        new Player { Name = "Nikola Vucevic", TeamID = 11, Age = 33, Height = "6-10", Position = "C" },
                        new Player { Name = "DeMar DeRozan", TeamID = 11, Age = 34, Height = "6-6", Position = "G-F" },
                        new Player { Name = "Ayo Dosunmu", TeamID = 11, Age = 23, Height = "6-5", Position = "G" },
                        new Player { Name = "Torrey Craig", TeamID = 11, Age = 32, Height = "6-5", Position = "F" },
                        new Player { Name = "Julian Phillips", TeamID = 11, Age = 20, Height = "6-8", Position = "F" },
                        new Player { Name = "Onuralp Bitim", TeamID = 11, Age = 24, Height = "6-6", Position = "F" },
                        new Player { Name = "Adama Sanogo", TeamID = 11, Age = 21, Height = "6-9", Position = "F" },
                        new Player { Name = "Dalen Terry", TeamID = 11, Age = 21, Height = "6-7", Position = "F" },
                        new Player { Name = "Terry Taylor", TeamID = 11, Age = 24, Height = "6-4", Position = "F" },
                        new Player { Name = "Justin Lewis", TeamID = 11, Age = 21, Height = "6-7", Position = "F" },
                        new Player { Name = "Patrick Williams", TeamID = 11, Age = 22, Height = "6-7", Position = "F" },
                        new Player { Name = "Max Strus", TeamID = 12, Age = 27, Height = "6-5", Position = "G-F" },
                        new Player { Name = "Ty Jerome", TeamID = 12, Age = 26, Height = "6-5", Position = "G-F" },
                        new Player { Name = "Caris LeVert", TeamID = 12, Age = 29, Height = "6-6", Position = "G" },
                        new Player { Name = "Evan Mobley", TeamID = 12, Age = 22, Height = "6-11", Position = "C" },
                        new Player { Name = "Sam Merrill", TeamID = 12, Age = 27, Height = "6-4", Position = "G" },
                        new Player { Name = "Craig Porter Jr.", TeamID = 12, Age = 23, Height = "6-1", Position = "G" },
                        new Player { Name = "Darius Garland", TeamID = 12, Age = 23, Height = "6-1", Position = "G" },
                        new Player { Name = "Tristan Thompson", TeamID = 12, Age = 32, Height = "6-9", Position = "C-F" },
                        new Player { Name = "Ricky Rubio", TeamID = 12, Age = 33, Height = "6-2", Position = "G" },
                        new Player { Name = "Isaiah Mobley", TeamID = 12, Age = 24, Height = "6-8", Position = "F" },
                        new Player { Name = "Georges Niang", TeamID = 12, Age = 30, Height = "6-7", Position = "F" },
                        new Player { Name = "Emoni Bates", TeamID = 12, Age = 19, Height = "6-8", Position = "F" },
                        new Player { Name = "Damian Jones", TeamID = 12, Age = 28, Height = "6-10", Position = "C" },
                        new Player { Name = "Jarrett Allen", TeamID = 12, Age = 25, Height = "6-9", Position = "C" },
                        new Player { Name = "Dean Wade", TeamID = 12, Age = 27, Height = "6-9", Position = "F-C" },
                        new Player { Name = "Isaac Okoro", TeamID = 12, Age = 22, Height = "6-5", Position = "F-G" },
                        new Player { Name = "Donovan Mitchell", TeamID = 12, Age = 27, Height = "6-3", Position = "G" },
                        new Player { Name = "Jalen Duren", TeamID = 13, Age = 20, Height = "6-10", Position = "C" },
                        new Player { Name = "Cade Cunningham", TeamID = 13, Age = 22, Height = "6-6", Position = "G" },
                        new Player { Name = "Monte Morris", TeamID = 13, Age = 28, Height = "6-2", Position = "G" },
                        new Player { Name = "Killian Hayes", TeamID = 13, Age = 22, Height = "6-5", Position = "G" },
                        new Player { Name = "Jared Rhoden", TeamID = 13, Age = 24, Height = "6-5", Position = "G" },
                        new Player { Name = "Ausar Thompson", TeamID = 13, Age = 20, Height = "6-6", Position = "G-F" },
                        new Player { Name = "Isaiah Livers", TeamID = 13, Age = 25, Height = "6-6", Position = "F" },
                        new Player { Name = "James Wiseman", TeamID = 13, Age = 22, Height = "6-11", Position = "C" },
                        new Player { Name = "Alec Burks", TeamID = 13, Age = 32, Height = "6-5", Position = "G" },
                        new Player { Name = "Stanley Umude", TeamID = 13, Age = 24, Height = "6-6", Position = "G" },
                        new Player { Name = "Malcolm Cazalon", TeamID = 13, Age = 22, Height = "6-6", Position = "G" },
                        new Player { Name = "Jaden Ivey", TeamID = 13, Age = 21, Height = "6-4", Position = "G" },
                        new Player { Name = "Kevin Knox II", TeamID = 13, Age = 24, Height = "6-7", Position = "F" },
                        new Player { Name = "Marcus Sasser", TeamID = 13, Age = 23, Height = "6-2", Position = "G" },
                        new Player { Name = "Isaiah Stewart", TeamID = 13, Age = 22, Height = "6-8", Position = "F-C" },
                        new Player { Name = "Joe Harris", TeamID = 13, Age = 32, Height = "6-6", Position = "G-F" },
                        new Player { Name = "Marvin Bagley III", TeamID = 13, Age = 24, Height = "6-10", Position = "F" },
                        new Player { Name = "Bojan Bogdanovic", TeamID = 13, Age = 34, Height = "6-7", Position = "F" },
                        new Player { Name = "Tyrese Haliburton", TeamID = 14, Age = 23, Height = "6-5", Position = "G" },
                        new Player { Name = "Bennedict Mathurin", TeamID = 14, Age = 21, Height = "6-5", Position = "G-F" },
                        new Player { Name = "Obi Toppin", TeamID = 14, Age = 25, Height = "6-9", Position = "F" },
                        new Player { Name = "Andrew Nembhard", TeamID = 14, Age = 23, Height = "6-4", Position = "G-F" },
                        new Player { Name = "Jarace Walker", TeamID = 14, Age = 20, Height = "6-7", Position = "F" },
                        new Player { Name = "Buddy Hield", TeamID = 14, Age = 30, Height = "6-4", Position = "G" },
                        new Player { Name = "T.J. McConnell", TeamID = 14, Age = 31, Height = "6-1", Position = "G" },
                        new Player { Name = "Kendall Brown", TeamID = 14, Age = 20, Height = "6-7", Position = "G" },
                        new Player { Name = "Bruce Brown", TeamID = 14, Age = 27, Height = "6-4", Position = "G-F" },
                        new Player { Name = "Jordan Nwora", TeamID = 14, Age = 25, Height = "6-8", Position = "F" },
                        new Player { Name = "Isaiah Wong", TeamID = 14, Age = 22, Height = "6-3", Position = "G" },
                        new Player { Name = "Isaiah Jackson", TeamID = 14, Age = 21, Height = "6-9", Position = "F" },
                        new Player { Name = "Aaron Nesmith", TeamID = 14, Age = 24, Height = "6-6", Position = "G-F" },
                        new Player { Name = "Jalen Smith", TeamID = 14, Age = 23, Height = "6-9", Position = "F-C" },
                        new Player { Name = "Ben Sheppard", TeamID = 14, Age = 22, Height = "6-6", Position = "G" },
                        new Player { Name = "Myles Turner", TeamID = 14, Age = 27, Height = "6-11", Position = "C-F" },
                        new Player { Name = "Oscar Tshiebwe", TeamID = 14, Age = 24, Height = "6-8", Position = "F-C" },
                        new Player { Name = "Damian Lillard", TeamID = 15, Age = 33, Height = "6-2", Position = "G" },
                        new Player { Name = "MarJon Beauchamp", TeamID = 15, Age = 23, Height = "6-7", Position = "F" },
                        new Player { Name = "Malik Beasley", TeamID = 15, Age = 27, Height = "6-4", Position = "G" },
                        new Player { Name = "Chris Livingston", TeamID = 15, Age = 20, Height = "6-6", Position = "F" },
                        new Player { Name = "Bobby Portis", TeamID = 15, Age = 28, Height = "6-10", Position = "F" },
                        new Player { Name = "Brook Lopez", TeamID = 15, Age = 35, Height = "7-1", Position = "C" },
                        new Player { Name = "Marques Bolden", TeamID = 15, Age = 25, Height = "6-10", Position = "C" },
                        new Player { Name = "Cameron Payne", TeamID = 15, Age = 29, Height = "6-3", Position = "G" },
                        new Player { Name = "AJ Green", TeamID = 15, Age = 24, Height = "6-4", Position = "G" },
                        new Player { Name = "Khris Middleton", TeamID = 15, Age = 32, Height = "6-7", Position = "F" },
                        new Player { Name = "TyTy Washington Jr.", TeamID = 15, Age = 22, Height = "6-3", Position = "G" },
                        new Player { Name = "Pat Connaughton", TeamID = 15, Age = 30, Height = "6-5", Position = "G" },
                        new Player { Name = "Lindell Wigginton", TeamID = 15, Age = 25, Height = "6-1", Position = "G" },
                        new Player { Name = "Giannis Antetokounmpo", TeamID = 15, Age = 28, Height = "6-11", Position = "F" },
                        new Player { Name = "Robin Lopez", TeamID = 15, Age = 35, Height = "7-1", Position = "C" },
                        new Player { Name = "Thanasis Antetokounmpo", TeamID = 15, Age = 31, Height = "6-7", Position = "F" },
                        new Player { Name = "Andre Jackson Jr.", TeamID = 15, Age = 22, Height = "6-6", Position = "G" },
                        new Player { Name = "Jae Crowder", TeamID = 15, Age = 33, Height = "6-6", Position = "F" },
                        new Player { Name = "Miles Norris", TeamID = 16, Age = 23, Height = "6-7", Position = "F" },
                        new Player { Name = "Jalen Johnson", TeamID = 16, Age = 21, Height = "6-8", Position = "F" },
                        new Player { Name = "Trent Forrest", TeamID = 16, Age = 25, Height = "6-4", Position = "G" },
                        new Player { Name = "Seth Lundy", TeamID = 16, Age = 23, Height = "6-4", Position = "G-F" },
                        new Player { Name = "Kobe Bufkin", TeamID = 16, Age = 20, Height = "6-5", Position = "G" },
                        new Player { Name = "Dejounte Murray", TeamID = 16, Age = 27, Height = "6-5", Position = "G" },
                        new Player { Name = "Patty Mills", TeamID = 16, Age = 35, Height = "6-2", Position = "G" },
                        new Player { Name = "Trae Young", TeamID = 16, Age = 25, Height = "6-1", Position = "G" },
                        new Player { Name = "De'Andre Hunter", TeamID = 16, Age = 26, Height = "6-8", Position = "F-G" },
                        new Player { Name = "Bogdan Bogdanovic", TeamID = 16, Age = 31, Height = "6-5", Position = "G" },
                        new Player { Name = "AJ Griffin", TeamID = 16, Age = 20, Height = "6-6", Position = "F" },
                        new Player { Name = "Clint Capela", TeamID = 16, Age = 29, Height = "6-10", Position = "C" },
                        new Player { Name = "Onyeka Okongwu", TeamID = 16, Age = 22, Height = "6-10", Position = "F-C" },
                        new Player { Name = "Mouhamed Gueye", TeamID = 16, Age = 21, Height = "6-10", Position = "F" },
                        new Player { Name = "Bruno Fernando", TeamID = 16, Age = 25, Height = "6-9", Position = "F-C" },
                        new Player { Name = "Garrison Mathews", TeamID = 16, Age = 27, Height = "6-6", Position = "G" },
                        new Player { Name = "Wesley Matthews", TeamID = 16, Age = 37, Height = "6-5", Position = "G" },
                        new Player { Name = "Saddiq Bey", TeamID = 16, Age = 24, Height = "6-7", Position = "G-F" },
                        new Player { Name = "Miles Bridges", TeamID = 17, Age = 25, Height = "6-7", Position = "F" },
                        new Player { Name = "LaMelo Ball", TeamID = 17, Age = 22, Height = "6-7", Position = "G" },
                        new Player { Name = "James Bouknight", TeamID = 17, Age = 23, Height = "6-4", Position = "G" },
                        new Player { Name = "Terry Rozier", TeamID = 17, Age = 29, Height = "6-1", Position = "G" },
                        new Player { Name = "Nick Richards", TeamID = 17, Age = 26, Height = "7-0", Position = "C" },
                        new Player { Name = "Mark Williams", TeamID = 17, Age = 21, Height = "7-0", Position = "C" },
                        new Player { Name = "Bryce McGowens", TeamID = 17, Age = 21, Height = "6-6", Position = "G" },
                        new Player { Name = "Nick Smith Jr.", TeamID = 17, Age = 19, Height = "6-2", Position = "G" },
                        new Player { Name = "Theo Maledon", TeamID = 17, Age = 22, Height = "6-4", Position = "G" },
                        new Player { Name = "Amari Bailey", TeamID = 17, Age = 19, Height = "6-3", Position = "G" },
                        new Player { Name = "Cody Martin", TeamID = 17, Age = 28, Height = "6-6", Position = "F" },
                        new Player { Name = "Leaky Black", TeamID = 17, Age = 24, Height = "6-6", Position = "F" },
                        new Player { Name = "Ish Smith", TeamID = 17, Age = 35, Height = "6-0", Position = "G" },
                        new Player { Name = "Gordon Hayward", TeamID = 17, Age = 33, Height = "6-7", Position = "F" },
                        new Player { Name = "JT Thor", TeamID = 17, Age = 21, Height = "6-9", Position = "F" },
                        new Player { Name = "Brandon Miller", TeamID = 17, Age = 21, Height = "6-7", Position = "F" },
                        new Player { Name = "P.J. Washington", TeamID = 17, Age = 25, Height = "6-7", Position = "F" },
                        new Player { Name = "Frank Ntilikina", TeamID = 17, Age = 25, Height = "6-4", Position = "G" },
                        new Player { Name = "Josh Richardson", TeamID = 18, Age = 30, Height = "6-5", Position = "G" },
                        new Player { Name = "R.J. Hampton", TeamID = 18, Age = 22, Height = "6-4", Position = "G" },
                        new Player { Name = "Nikola Jovic", TeamID = 18, Age = 20, Height = "6-10", Position = "F" },
                        new Player { Name = "Kyle Lowry", TeamID = 18, Age = 37, Height = "6-0", Position = "G" },
                        new Player { Name = "Jamal Cain", TeamID = 18, Age = 24, Height = "6-6", Position = "F" },
                        new Player { Name = "Dru Smith", TeamID = 18, Age = 25, Height = "6-2", Position = "G" },
                        new Player { Name = "Jaime Jaquez Jr.", TeamID = 18, Age = 22, Height = "6-6", Position = "G" },
                        new Player { Name = "Bam Adebayo", TeamID = 18, Age = 26, Height = "6-9", Position = "C-F" },
                        new Player { Name = "Tyler Herro", TeamID = 18, Age = 23, Height = "6-5", Position = "G" },
                        new Player { Name = "Caleb Martin", TeamID = 18, Age = 28, Height = "6-5", Position = "F" },
                        new Player { Name = "Cole Swider", TeamID = 18, Age = 24, Height = "6-8", Position = "F" },
                        new Player { Name = "Jimmy Butler", TeamID = 18, Age = 34, Height = "6-7", Position = "F" },
                        new Player { Name = "Haywood Highsmith", TeamID = 18, Age = 26, Height = "6-5", Position = "F" },
                        new Player { Name = "Orlando Robinson", TeamID = 18, Age = 23, Height = "6-10", Position = "C" },
                        new Player { Name = "Thomas Bryant", TeamID = 18, Age = 26, Height = "6-10", Position = "C-F" },
                        new Player { Name = "Kevin Love", TeamID = 18, Age = 35, Height = "6-8", Position = "F-C" },
                        new Player { Name = "Duncan Robinson", TeamID = 18, Age = 29, Height = "6-7", Position = "F" },
                        new Player { Name = "Anthony Black", TeamID = 19, Age = 19, Height = "6-7", Position = "G" },
                        new Player { Name = "Jonathan Isaac", TeamID = 19, Age = 26, Height = "6-10", Position = "F" },
                        new Player { Name = "Caleb Houstan", TeamID = 19, Age = 20, Height = "6-8", Position = "G" },
                        new Player { Name = "Chuma Okeke", TeamID = 19, Age = 25, Height = "6-7", Position = "F" },
                        new Player { Name = "Jalen Suggs", TeamID = 19, Age = 22, Height = "6-5", Position = "G" },
                        new Player { Name = "Paolo Banchero", TeamID = 19, Age = 21, Height = "6-10", Position = "F" },
                        new Player { Name = "Joe Ingles", TeamID = 19, Age = 36, Height = "6-9", Position = "F-G" },
                        new Player { Name = "Kevon Harris", TeamID = 19, Age = 26, Height = "6-5", Position = "G" },
                        new Player { Name = "Trevelin Queen", TeamID = 19, Age = 26, Height = "6-5", Position = "G" },
                        new Player { Name = "Jett Howard", TeamID = 19, Age = 20, Height = "6-6", Position = "G" },
                        new Player { Name = "Gary Harris", TeamID = 19, Age = 29, Height = "6-4", Position = "G" },
                        new Player { Name = "Markelle Fultz", TeamID = 19, Age = 25, Height = "6-4", Position = "G" },
                        new Player { Name = "Moritz Wagner", TeamID = 19, Age = 26, Height = "6-11", Position = "F-C" },
                        new Player { Name = "Franz Wagner", TeamID = 19, Age = 22, Height = "6-10", Position = "F" },
                        new Player { Name = "Admiral Schofield", TeamID = 19, Age = 26, Height = "6-5", Position = "F" },
                        new Player { Name = "Wendell Carter Jr.", TeamID = 19, Age = 24, Height = "6-10", Position = "C-F" },
                        new Player { Name = "Goga Bitadze", TeamID = 19, Age = 24, Height = "6-10", Position = "C-F" },
                        new Player { Name = "Cole Anthony", TeamID = 19, Age = 23, Height = "6-2", Position = "G" },
                        new Player { Name = "Bilal Coulibaly", TeamID = 20, Age = 19, Height = "6-8", Position = "G" },
                        new Player { Name = "Johnny Davis", TeamID = 20, Age = 21, Height = "6-4", Position = "G" },
                        new Player { Name = "Jared Butler", TeamID = 20, Age = 23, Height = "6-3", Position = "G" },
                        new Player { Name = "Tyus Jones", TeamID = 20, Age = 27, Height = "6-1", Position = "G" },
                        new Player { Name = "Patrick Baldwin Jr.", TeamID = 20, Age = 21, Height = "6-9", Position = "F" },
                        new Player { Name = "Deni Avdija", TeamID = 20, Age = 22, Height = "6-9", Position = "F" },
                        new Player { Name = "Ryan Rollins", TeamID = 20, Age = 21, Height = "6-3", Position = "G" },
                        new Player { Name = "Jordan Poole", TeamID = 20, Age = 24, Height = "6-4", Position = "G" },
                        new Player { Name = "Anthony Gill", TeamID = 20, Age = 31, Height = "6-8", Position = "F" },
                        new Player { Name = "John Butler Jr.", TeamID = 20, Age = 20, Height = "7-0", Position = "F" },
                        new Player { Name = "Landry Shamet", TeamID = 20, Age = 26, Height = "6-4", Position = "G" },
                        new Player { Name = "Daniel Gafford", TeamID = 20, Age = 25, Height = "6-10", Position = "F-C" },
                        new Player { Name = "Corey Kispert", TeamID = 20, Age = 24, Height = "6-6", Position = "F" },
                        new Player { Name = "Kyle Kuzma", TeamID = 20, Age = 28, Height = "6-9", Position = "F" },
                        new Player { Name = "Mike Muscala", TeamID = 20, Age = 32, Height = "6-10", Position = "F-C" },
                        new Player { Name = "Delon Wright", TeamID = 20, Age = 31, Height = "6-5", Position = "G" },
                        new Player { Name = "Danilo Gallinari", TeamID = 20, Age = 35, Height = "6-10", Position = "F" },
                        new Player { Name = "Eugene Omoruyi", TeamID = 20, Age = 26, Height = "6-6", Position = "F" },
                        new Player { Name = "Christian Braun", TeamID = 21, Age = 22, Height = "6-6", Position = "G" },
                        new Player { Name = "Michael Porter Jr.", TeamID = 21, Age = 25, Height = "6-10", Position = "F" },
                        new Player { Name = "Julian Strawther", TeamID = 21, Age = 21, Height = "6-6", Position = "G" },
                        new Player { Name = "Hunter Tyson", TeamID = 21, Age = 23, Height = "6-8", Position = "F" },
                        new Player { Name = "Kentavious Caldwell-Pope", TeamID = 21, Age = 30, Height = "6-5", Position = "G" },
                        new Player { Name = "DeAndre Jordan", TeamID = 21, Age = 35, Height = "6-11", Position = "C" },
                        new Player { Name = "Reggie Jackson", TeamID = 21, Age = 33, Height = "6-2", Position = "G" },
                        new Player { Name = "Peyton Watson", TeamID = 21, Age = 21, Height = "6-7", Position = "G" },
                        new Player { Name = "Justin Holiday", TeamID = 21, Age = 34, Height = "6-6", Position = "F-G" },
                        new Player { Name = "Braxton Key", TeamID = 21, Age = 26, Height = "6-8", Position = "F" },
                        new Player { Name = "Nikola Jokic", TeamID = 21, Age = 28, Height = "6-11", Position = "C" },
                        new Player { Name = "Collin Gillespie", TeamID = 21, Age = 24, Height = "6-1", Position = "G" },
                        new Player { Name = "Zeke Nnaji", TeamID = 21, Age = 22, Height = "6-9", Position = "F-C" },
                        new Player { Name = "Jalen Pickett", TeamID = 21, Age = 24, Height = "6-2", Position = "G" },
                        new Player { Name = "Jamal Murray", TeamID = 21, Age = 26, Height = "6-4", Position = "G" },
                        new Player { Name = "Jay Huff", TeamID = 21, Age = 26, Height = "7-1", Position = "C" },
                        new Player { Name = "Vlatko Cancar", TeamID = 21, Age = 26, Height = "6-8", Position = "F" },
                        new Player { Name = "Aaron Gordon", TeamID = 21, Age = 28, Height = "6-8", Position = "F" },
                        new Player { Name = "Jaylen Clark", TeamID = 22, Age = 22, Height = "6-4", Position = "G" },
                        new Player { Name = "Kyle Anderson", TeamID = 22, Age = 30, Height = "6-9", Position = "F-G" },
                        new Player { Name = "Jaden McDaniels", TeamID = 22, Age = 23, Height = "6-9", Position = "F" },
                        new Player { Name = "Anthony Edwards", TeamID = 22, Age = 22, Height = "6-4", Position = "G" },
                        new Player { Name = "Jordan McLaughlin", TeamID = 22, Age = 27, Height = "6-0", Position = "G" },
                        new Player { Name = "Wendell Moore Jr.", TeamID = 22, Age = 22, Height = "6-5", Position = "G" },
                        new Player { Name = "Josh Minott", TeamID = 22, Age = 21, Height = "6-8", Position = "F" },
                        new Player { Name = "Nickeil Alexander-Walker", TeamID = 22, Age = 25, Height = "6-5", Position = "G" },
                        new Player { Name = "Mike Conley", TeamID = 22, Age = 36, Height = "6-0", Position = "G" },
                        new Player { Name = "Naz Reid", TeamID = 22, Age = 24, Height = "6-9", Position = "C-F" },
                        new Player { Name = "Daishen Nix", TeamID = 22, Age = 21, Height = "6-3", Position = "G" },
                        new Player { Name = "Shake Milton", TeamID = 22, Age = 27, Height = "6-5", Position = "G-F" },
                        new Player { Name = "Troy Brown Jr.", TeamID = 22, Age = 24, Height = "6-7", Position = "G-F" },
                        new Player { Name = "Rudy Gobert", TeamID = 22, Age = 31, Height = "7-1", Position = "C" },
                        new Player { Name = "Karl-Anthony Towns", TeamID = 22, Age = 28, Height = "7-0", Position = "C-F" },
                        new Player { Name = "Leonard Miller", TeamID = 22, Age = 20, Height = "6-10", Position = "F" },
                        new Player { Name = "Luka Garza", TeamID = 22, Age = 24, Height = "6-10", Position = "C" },
                        new Player { Name = "Shai Gilgeous-Alexander", TeamID = 23, Age = 25, Height = "6-6", Position = "G" },
                        new Player { Name = "Josh Giddey", TeamID = 23, Age = 21, Height = "6-8", Position = "G" },
                        new Player { Name = "Luguentz Dort", TeamID = 23, Age = 24, Height = "6-4", Position = "G" },
                        new Player { Name = "Jaylin Williams", TeamID = 23, Age = 21, Height = "6-9", Position = "F" },
                        new Player { Name = "Chet Holmgren", TeamID = 23, Age = 21, Height = "7-1", Position = "C-F" },
                        new Player { Name = "Jalen Williams", TeamID = 23, Age = 22, Height = "6-5", Position = "G-F" },
                        new Player { Name = "Davis Bertans", TeamID = 23, Age = 31, Height = "6-10", Position = "F" },
                        new Player { Name = "Isaiah Joe", TeamID = 23, Age = 24, Height = "6-3", Position = "G" },
                        new Player { Name = "Lindy Waters III", TeamID = 23, Age = 26, Height = "6-6", Position = "F" },
                        new Player { Name = "Ousmane Dieng", TeamID = 23, Age = 20, Height = "6-9", Position = "F" },
                        new Player { Name = "Aleksej Pokusevski", TeamID = 23, Age = 21, Height = "7-0", Position = "F" },
                        new Player { Name = "Keyontae Johnson", TeamID = 23, Age = 23, Height = "6-4", Position = "F" },
                        new Player { Name = "Aaron Wiggins", TeamID = 23, Age = 24, Height = "6-5", Position = "G" },
                        new Player { Name = "Cason Wallace", TeamID = 23, Age = 20, Height = "6-3", Position = "G" },
                        new Player { Name = "Tre Mann", TeamID = 23, Age = 22, Height = "6-3", Position = "G" },
                        new Player { Name = "Vasilije Micic", TeamID = 23, Age = 29, Height = "6-3", Position = "G" },
                        new Player { Name = "Olivier Sarr", TeamID = 23, Age = 24, Height = "6-10", Position = "C" },
                        new Player { Name = "Kenrich Williams", TeamID = 23, Age = 29, Height = "6-6", Position = "G-F" },
                        new Player { Name = "Scoot Henderson", TeamID = 24, Age = 19, Height = "6-3", Position = "G" },
                        new Player { Name = "Anfernee Simons", TeamID = 24, Age = 24, Height = "6-3", Position = "G" },
                        new Player { Name = "Deandre Ayton", TeamID = 24, Age = 25, Height = "7-0", Position = "C" },
                        new Player { Name = "Matisse Thybulle", TeamID = 24, Age = 26, Height = "6-5", Position = "G-F" },
                        new Player { Name = "Skylar Mays", TeamID = 24, Age = 26, Height = "6-3", Position = "G" },
                        new Player { Name = "Kris Murray", TeamID = 24, Age = 23, Height = "6-8", Position = "F" },
                        new Player { Name = "Jerami Grant", TeamID = 24, Age = 29, Height = "6-7", Position = "F" },
                        new Player { Name = "Moses Brown", TeamID = 24, Age = 24, Height = "7-2", Position = "C" },
                        new Player { Name = "Malcolm Brogdon", TeamID = 24, Age = 30, Height = "6-4", Position = "G" },
                        new Player { Name = "Shaedon Sharpe", TeamID = 24, Age = 20, Height = "6-5", Position = "G" },
                        new Player { Name = "Ish Wainright", TeamID = 24, Age = 29, Height = "6-5", Position = "F" },
                        new Player { Name = "Justin Minaya", TeamID = 24, Age = 24, Height = "6-5", Position = "F" },
                        new Player { Name = "Duop Reath", TeamID = 24, Age = 27, Height = "6-9", Position = "C" },
                        new Player { Name = "Toumani Camara", TeamID = 24, Age = 23, Height = "6-7", Position = "F" },
                        new Player { Name = "Jabari Walker", TeamID = 24, Age = 21, Height = "6-7", Position = "F" },
                        new Player { Name = "Robert Williams III", TeamID = 24, Age = 26, Height = "6-9", Position = "C-F" },
                        new Player { Name = "Ibou Badji", TeamID = 24, Age = 21, Height = "7-0", Position = "C" },
                        new Player { Name = "Rayan Rupert", TeamID = 24, Age = 19, Height = "6-6", Position = "G-F" },
                        new Player { Name = "Jordan Clarkson", TeamID = 25, Age = 31, Height = "6-3", Position = "G" },
                        new Player { Name = "Taylor Hendricks", TeamID = 25, Age = 20, Height = "6-9", Position = "F" },
                        new Player { Name = "Collin Sexton", TeamID = 25, Age = 24, Height = "6-3", Position = "G" },
                        new Player { Name = "Keyonte George", TeamID = 25, Age = 20, Height = "6-4", Position = "G" },
                        new Player { Name = "Talen Horton-Tucker", TeamID = 25, Age = 23, Height = "6-4", Position = "G" },
                        new Player { Name = "Brice Sensabaugh", TeamID = 25, Age = 20, Height = "6-5", Position = "F" },
                        new Player { Name = "Kris Dunn", TeamID = 25, Age = 29, Height = "6-3", Position = "G" },
                        new Player { Name = "Josh Christopher", TeamID = 25, Age = 21, Height = "6-4", Position = "G" },
                        new Player { Name = "Simone Fontecchio", TeamID = 25, Age = 27, Height = "6-7", Position = "F" },
                        new Player { Name = "Luka Samanic", TeamID = 25, Age = 23, Height = "6-10", Position = "F" },
                        new Player { Name = "John Collins", TeamID = 25, Age = 26, Height = "6-9", Position = "F-C" },
                        new Player { Name = "Lauri Markkanen", TeamID = 25, Age = 26, Height = "7-0", Position = "F-C" },
                        new Player { Name = "Walker Kessler", TeamID = 25, Age = 22, Height = "7-0", Position = "C" },
                        new Player { Name = "Micah Potter", TeamID = 25, Age = 25, Height = "6-9", Position = "C" },
                        new Player { Name = "Ochai Agbaji", TeamID = 25, Age = 23, Height = "6-5", Position = "G" },
                        new Player { Name = "Johnny Juzang", TeamID = 25, Age = 22, Height = "6-5", Position = "G" },
                        new Player { Name = "Kelly Olynyk", TeamID = 25, Age = 32, Height = "6-11", Position = "F-C" },
                        new Player { Name = "Omer Yurtseven", TeamID = 25, Age = 25, Height = "6-11", Position = "C" },
                        new Player { Name = "Gary Payton II", TeamID = 26, Age = 31, Height = "6-2", Position = "G" },
                        new Player { Name = "Jonathan Kuminga", TeamID = 26, Age = 21, Height = "6-7", Position = "F" },
                        new Player { Name = "Cory Joseph", TeamID = 26, Age = 32, Height = "6-2", Position = "G" },
                        new Player { Name = "Brandin Podziemski", TeamID = 26, Age = 20, Height = "6-4", Position = "G" },
                        new Player { Name = "Chris Paul", TeamID = 26, Age = 38, Height = "6-0", Position = "G" },
                        new Player { Name = "Moses Moody", TeamID = 26, Age = 21, Height = "6-5", Position = "G" },
                        new Player { Name = "Kevon Looney", TeamID = 26, Age = 27, Height = "6-9", Position = "F" },
                        new Player { Name = "Klay Thompson", TeamID = 26, Age = 33, Height = "6-6", Position = "G" },
                        new Player { Name = "Usman Garuba", TeamID = 26, Age = 21, Height = "6-8", Position = "F" },
                        new Player { Name = "Gui Santos", TeamID = 26, Age = 21, Height = "6-6", Position = "F" },
                        new Player { Name = "Jerome Robinson", TeamID = 26, Age = 26, Height = "6-5", Position = "G" },
                        new Player { Name = "Dario Saric", TeamID = 26, Age = 29, Height = "6-10", Position = "F-C" },
                        new Player { Name = "Andrew Wiggins", TeamID = 26, Age = 28, Height = "6-7", Position = "F" },
                        new Player { Name = "Draymond Green", TeamID = 26, Age = 33, Height = "6-6", Position = "F" },
                        new Player { Name = "Lester Quinones", TeamID = 26, Age = 23, Height = "6-4", Position = "G" },
                        new Player { Name = "Stephen Curry", TeamID = 26, Age = 35, Height = "6-2", Position = "G" },
                        new Player { Name = "Trayce Jackson-Davis", TeamID = 26, Age = 23, Height = "6-9", Position = "F" },
                        new Player { Name = "Russell Westbrook", TeamID = 34, Age = 35, Height = "6-4", Position = "G" },
                        new Player { Name = "James Harden", TeamID = 34, Age = 34, Height = "6-5", Position = "G" },
                        new Player { Name = "Kawhi Leonard", TeamID = 34, Age = 32, Height = "6-7", Position = "F" },
                        new Player { Name = "Brandon Boston Jr.", TeamID = 34, Age = 22, Height = "6-6", Position = "G" },
                        new Player { Name = "Bones Hyland", TeamID = 34, Age = 23, Height = "6-2", Position = "G" },
                        new Player { Name = "Amir Coffey", TeamID = 34, Age = 26, Height = "6-7", Position = "G-F" },
                        new Player { Name = "Daniel Theis", TeamID = 34, Age = 31, Height = "6-8", Position = "F-C" },
                        new Player { Name = "Jordan Miller", TeamID = 34, Age = 23, Height = "6-5", Position = "G" },
                        new Player { Name = "Joshua Primo", TeamID = 34, Age = 20, Height = "6-4", Position = "G" },
                        new Player { Name = "Paul George", TeamID = 34, Age = 33, Height = "6-8", Position = "F" },
                        new Player { Name = "Terance Mann", TeamID = 34, Age = 27, Height = "6-5", Position = "G-F" },
                        new Player { Name = "Xavier Moon", TeamID = 34, Age = 28, Height = "6-0", Position = "G" },
                        new Player { Name = "P.J. Tucker", TeamID = 34, Age = 38, Height = "6-5", Position = "F" },
                        new Player { Name = "Kobe Brown", TeamID = 34, Age = 23, Height = "6-7", Position = "F" },
                        new Player { Name = "Norman Powell", TeamID = 34, Age = 30, Height = "6-4", Position = "G" },
                        new Player { Name = "Moussa Diabate", TeamID = 34, Age = 21, Height = "6-9", Position = "F" },
                        new Player { Name = "Ivica Zubac", TeamID = 34, Age = 26, Height = "7-0", Position = "C" },
                        new Player { Name = "Mason Plumlee", TeamID = 34, Age = 33, Height = "6-10", Position = "F-C" },
                        new Player { Name = "Jalen Hood-Schifino", TeamID = 6, Age = 20, Height = "6-5", Position = "G" },
                        new Player { Name = "D'Angelo Russell", TeamID = 6, Age = 27, Height = "6-3", Position = "G" },
                        new Player { Name = "Jarred Vanderbilt", TeamID = 6, Age = 24, Height = "6-8", Position = "F" },
                        new Player { Name = "Anthony Davis", TeamID = 6, Age = 30, Height = "6-10", Position = "F-C" },
                        new Player { Name = "Cam Reddish", TeamID = 6, Age = 24, Height = "6-7", Position = "F-G" },
                        new Player { Name = "Gabe Vincent", TeamID = 6, Age = 27, Height = "6-2", Position = "G" },
                        new Player { Name = "Max Christie", TeamID = 6, Age = 20, Height = "6-5", Position = "G" },
                        new Player { Name = "Jaxson Hayes", TeamID = 6, Age = 23, Height = "7-0", Position = "C-F" },
                        new Player { Name = "Taurean Prince", TeamID = 6, Age = 29, Height = "6-6", Position = "F" },
                        new Player { Name = "Colin Castleton", TeamID = 6, Age = 23, Height = "6-10", Position = "C" },
                        new Player { Name = "Austin Reaves", TeamID = 6, Age = 25, Height = "6-5", Position = "G" },
                        new Player { Name = "Alex Fudge", TeamID = 6, Age = 20, Height = "6-8", Position = "F" },
                        new Player { Name = "Maxwell Lewis", TeamID = 6, Age = 21, Height = "6-7", Position = "F" },
                        new Player { Name = "LeBron James", TeamID = 6, Age = 38, Height = "6-9", Position = "F" },
                        new Player { Name = "Rui Hachimura", TeamID = 6, Age = 25, Height = "6-8", Position = "F" },
                        new Player { Name = "Christian Wood", TeamID = 6, Age = 28, Height = "6-8", Position = "F" },
                        new Player { Name = "D'Moi Hodge", TeamID = 6, Age = 24, Height = "6-3", Position = "G" },
                        new Player { Name = "Jordan Goodwin", TeamID = 27, Age = 25, Height = "6-4", Position = "G" },
                        new Player { Name = "Devin Booker", TeamID = 27, Age = 27, Height = "6-6", Position = "G" },
                        new Player { Name = "Josh Okogie", TeamID = 27, Age = 25, Height = "6-4", Position = "G" },
                        new Player { Name = "Bradley Beal", TeamID = 27, Age = 30, Height = "6-4", Position = "G" },
                        new Player { Name = "Chimezie Metu", TeamID = 27, Age = 26, Height = "6-10", Position = "F-C" },
                        new Player { Name = "Grayson Allen", TeamID = 27, Age = 28, Height = "6-4", Position = "G" },
                        new Player { Name = "Damion Lee", TeamID = 27, Age = 31, Height = "6-6", Position = "G-F" },
                        new Player { Name = "Bol Bol", TeamID = 27, Age = 24, Height = "7-3", Position = "C-F" },
                        new Player { Name = "Drew Eubanks", TeamID = 27, Age = 26, Height = "6-10", Position = "F-C" },
                        new Player { Name = "Yuta Watanabe", TeamID = 27, Age = 29, Height = "6-9", Position = "G-F" },
                        new Player { Name = "Jusuf Nurkic", TeamID = 27, Age = 29, Height = "7-0", Position = "C" },
                        new Player { Name = "Keita Bates-Diop", TeamID = 27, Age = 27, Height = "6-8", Position = "F" },
                        new Player { Name = "Eric Gordon", TeamID = 27, Age = 34, Height = "6-3", Position = "G" },
                        new Player { Name = "Nassir Little", TeamID = 27, Age = 23, Height = "6-6", Position = "F-G" },
                        new Player { Name = "Udoka Azubuike", TeamID = 27, Age = 24, Height = "6-11", Position = "C-F" },
                        new Player { Name = "Kevin Durant", TeamID = 27, Age = 35, Height = "6-11", Position = "F" },
                        new Player { Name = "Saben Lee", TeamID = 27, Age = 24, Height = "6-2", Position = "G" },
                        new Player { Name = "Malik Monk", TeamID = 28, Age = 25, Height = "6-3", Position = "G" },
                        new Player { Name = "JaVale McGee", TeamID = 28, Age = 35, Height = "7-0", Position = "C-F" },
                        new Player { Name = "Chris Duarte", TeamID = 28, Age = 26, Height = "6-5", Position = "G" },
                        new Player { Name = "De'Aaron Fox", TeamID = 28, Age = 25, Height = "6-3", Position = "G" },
                        new Player { Name = "Sasha Vezenkov", TeamID = 28, Age = 28, Height = "6-8", Position = "F" },
                        new Player { Name = "Kevin Huerter", TeamID = 28, Age = 25, Height = "6-7", Position = "G-F" },
                        new Player { Name = "Domantas Sabonis", TeamID = 28, Age = 27, Height = "6-10", Position = "F-C" },
                        new Player { Name = "Keegan Murray", TeamID = 28, Age = 23, Height = "6-8", Position = "F" },
                        new Player { Name = "Davion Mitchell", TeamID = 28, Age = 25, Height = "6-0", Position = "G" },
                        new Player { Name = "Kessler Edwards", TeamID = 28, Age = 23, Height = "6-7", Position = "F" },
                        new Player { Name = "Jalen Slawson", TeamID = 28, Age = 24, Height = "6-7", Position = "F" },
                        new Player { Name = "Colby Jones", TeamID = 28, Age = 21, Height = "6-6", Position = "G" },
                        new Player { Name = "Keon Ellis", TeamID = 28, Age = 23, Height = "6-3", Position = "G" },
                        new Player { Name = "Alex Len", TeamID = 28, Age = 30, Height = "7-0", Position = "C" },
                        new Player { Name = "Jordan Ford", TeamID = 28, Age = 25, Height = "6-1", Position = "G" },
                        new Player { Name = "Harrison Barnes", TeamID = 28, Age = 31, Height = "6-8", Position = "F" },
                        new Player { Name = "Trey Lyles", TeamID = 28, Age = 28, Height = "6-9", Position = "F" },
                        new Player { Name = "Dante Exum", TeamID = 29, Age = 28, Height = "6-5", Position = "G" },
                        new Player { Name = "Jaden Hardy", TeamID = 29, Age = 21, Height = "6-3", Position = "G" },
                        new Player { Name = "Dereck Lively II", TeamID = 29, Age = 19, Height = "7-1", Position = "C" },
                        new Player { Name = "Grant Williams", TeamID = 29, Age = 25, Height = "6-6", Position = "F" },
                        new Player { Name = "Dwight Powell", TeamID = 29, Age = 32, Height = "6-10", Position = "F-C" },
                        new Player { Name = "Josh Green", TeamID = 29, Age = 23, Height = "6-5", Position = "G" },
                        new Player { Name = "A.J. Lawson", TeamID = 29, Age = 23, Height = "6-6", Position = "G" },
                        new Player { Name = "Tim Hardaway Jr.", TeamID = 29, Age = 31, Height = "6-5", Position = "G-F" },
                        new Player { Name = "Kyrie Irving", TeamID = 29, Age = 31, Height = "6-2", Position = "G" },
                        new Player { Name = "Olivier-Maxence Prosper", TeamID = 29, Age = 21, Height = "6-7", Position = "F" },
                        new Player { Name = "Richaun Holmes", TeamID = 29, Age = 30, Height = "6-9", Position = "F" },
                        new Player { Name = "Seth Curry", TeamID = 29, Age = 33, Height = "6-1", Position = "G" },
                        new Player { Name = "Greg Brown III", TeamID = 29, Age = 22, Height = "6-7", Position = "F" },
                        new Player { Name = "Dexter Dennis", TeamID = 29, Age = 24, Height = "6-5", Position = "G" },
                        new Player { Name = "Maxi Kleber", TeamID = 29, Age = 31, Height = "6-10", Position = "F" },
                        new Player { Name = "Derrick Jones Jr.", TeamID = 29, Age = 26, Height = "6-6", Position = "F" },
                        new Player { Name = "Luka Doncic", TeamID = 29, Age = 24, Height = "6-7", Position = "F-G" },
                        new Player { Name = "Markieff Morris", TeamID = 29, Age = 34, Height = "6-9", Position = "F" },
                        new Player { Name = "Jermaine Samuels Jr.", TeamID = 31, Age = 25, Height = "6-6", Position = "F" },
                        new Player { Name = "Aaron Holiday", TeamID = 31, Age = 27, Height = "6-0", Position = "G" },
                        new Player { Name = "Amen Thompson", TeamID = 31, Age = 20, Height = "6-7", Position = "G-F" },
                        new Player { Name = "Jock Landale", TeamID = 31, Age = 28, Height = "6-11", Position = "C" },
                        new Player { Name = "Victor Oladipo", TeamID = 31, Age = 31, Height = "6-3", Position = "G" },
                        new Player { Name = "Jalen Green", TeamID = 31, Age = 21, Height = "6-4", Position = "G" },
                        new Player { Name = "Fred VanVleet", TeamID = 31, Age = 29, Height = "6-0", Position = "G" },
                        new Player { Name = "Cam Whitmore", TeamID = 31, Age = 19, Height = "6-7", Position = "F" },
                        new Player { Name = "Jae'Sean Tate", TeamID = 31, Age = 28, Height = "6-4", Position = "F" },
                        new Player { Name = "Dillon Brooks", TeamID = 31, Age = 27, Height = "6-6", Position = "G-F" },
                        new Player { Name = "Jabari Smith Jr.", TeamID = 31, Age = 20, Height = "6-11", Position = "F" },
                        new Player { Name = "Nate Hinton", TeamID = 31, Age = 24, Height = "6-5", Position = "G-F" },
                        new Player { Name = "Tari Eason", TeamID = 31, Age = 22, Height = "6-8", Position = "F" },
                        new Player { Name = "Nate Williams", TeamID = 31, Age = 24, Height = "6-5", Position = "G" },
                        new Player { Name = "Reggie Bullock Jr.", TeamID = 31, Age = 32, Height = "6-6", Position = "G-F" },
                        new Player { Name = "Alperen Sengun", TeamID = 31, Age = 21, Height = "6-11", Position = "C" },
                        new Player { Name = "Jeff Green", TeamID = 31, Age = 37, Height = "6-8", Position = "F" },
                        new Player { Name = "Boban Marjanovic", TeamID = 31, Age = 35, Height = "7-4", Position = "C" },
                        new Player { Name = "Jacob Gilyard", TeamID = 30, Age = 25, Height = "5-8", Position = "G" },
                        new Player { Name = "Xavier Tillman", TeamID = 30, Age = 24, Height = "6-7", Position = "F" },
                        new Player { Name = "Jake LaRavia", TeamID = 30, Age = 22, Height = "6-7", Position = "F" },
                        new Player { Name = "Steven Adams", TeamID = 30, Age = 30, Height = "6-11", Position = "C" },
                        new Player { Name = "Vince Williams Jr.", TeamID = 30, Age = 23, Height = "6-4", Position = "G" },
                        new Player { Name = "Kenneth Lofton Jr.", TeamID = 30, Age = 21, Height = "6-6", Position = "F" },
                        new Player { Name = "Santi Aldama", TeamID = 30, Age = 22, Height = "7-0", Position = "F-C" },
                        new Player { Name = "Ziaire Williams", TeamID = 30, Age = 22, Height = "6-9", Position = "F" },
                        new Player { Name = "Luke Kennard", TeamID = 30, Age = 27, Height = "6-5", Position = "G" },
                        new Player { Name = "Ja Morant", TeamID = 30, Age = 24, Height = "6-2", Position = "G" },
                        new Player { Name = "Jaren Jackson Jr.", TeamID = 30, Age = 24, Height = "6-10", Position = "F-C" },
                        new Player { Name = "Brandon Clarke", TeamID = 30, Age = 27, Height = "6-8", Position = "F" },
                        new Player { Name = "Bismack Biyombo", TeamID = 30, Age = 31, Height = "6-8", Position = "C" },
                        new Player { Name = "David Roddy", TeamID = 30, Age = 22, Height = "6-4", Position = "F" },
                        new Player { Name = "Desmond Bane", TeamID = 30, Age = 25, Height = "6-5", Position = "G" },
                        new Player { Name = "Derrick Rose", TeamID = 30, Age = 35, Height = "6-3", Position = "G" },
                        new Player { Name = "Jaylen Nowell", TeamID = 30, Age = 24, Height = "6-4", Position = "G" },
                        new Player { Name = "Marcus Smart", TeamID = 30, Age = 29, Height = "6-3", Position = "G" },
                        new Player { Name = "GG Jackson", TeamID = 30, Age = 18, Height = "6-9", Position = "F" },
                        new Player { Name = "John Konchar", TeamID = 30, Age = 27, Height = "6-5", Position = "G" },
                        new Player { Name = "Dereon Seabron", TeamID = 32, Age = 23, Height = "6-5", Position = "G" },
                        new Player { Name = "Zion Williamson", TeamID = 32, Age = 23, Height = "6-6", Position = "F" },
                        new Player { Name = "CJ McCollum", TeamID = 32, Age = 32, Height = "6-3", Position = "G" },
                        new Player { Name = "Herbert Jones", TeamID = 32, Age = 25, Height = "6-7", Position = "F" },
                        new Player { Name = "Naji Marshall", TeamID = 32, Age = 25, Height = "6-6", Position = "F" },
                        new Player { Name = "Dyson Daniels", TeamID = 32, Age = 20, Height = "6-7", Position = "G" },
                        new Player { Name = "Kira Lewis Jr.", TeamID = 32, Age = 22, Height = "6-1", Position = "G" },
                        new Player { Name = "Brandon Ingram", TeamID = 32, Age = 26, Height = "6-8", Position = "F" },
                        new Player { Name = "Jose Alvarado", TeamID = 32, Age = 25, Height = "6-0", Position = "G" },
                        new Player { Name = "Jonas Valanciunas", TeamID = 32, Age = 31, Height = "6-11", Position = "C" },
                        new Player { Name = "Larry Nance Jr.", TeamID = 32, Age = 30, Height = "6-8", Position = "F-C" },
                        new Player { Name = "Jordan Hawkins", TeamID = 32, Age = 21, Height = "6-5", Position = "G" },
                        new Player { Name = "Trey Murphy III", TeamID = 32, Age = 23, Height = "6-8", Position = "F" },
                        new Player { Name = "E.J. Liddell", TeamID = 32, Age = 22, Height = "6-6", Position = "F" },
                        new Player { Name = "Matt Ryan", TeamID = 32, Age = 26, Height = "6-6", Position = "F" },
                        new Player { Name = "Cody Zeller", TeamID = 32, Age = 31, Height = "6-11", Position = "F-C" },
                        new Player { Name = "Jeremiah Robinson-Earl", TeamID = 32, Age = 23, Height = "6-8", Position = "F" },
                        new Player { Name = "Victor Wembanyama", TeamID = 33, Age = 19, Height = "7-4", Position = "F-C" },
                        new Player { Name = "Keldon Johnson", TeamID = 33, Age = 24, Height = "6-5", Position = "F-G" },
                        new Player { Name = "Devonte' Graham", TeamID = 33, Age = 28, Height = "6-1", Position = "G" },
                        new Player { Name = "Jeremy Sochan", TeamID = 33, Age = 20, Height = "6-8", Position = "F" },
                        new Player { Name = "Sir'Jabari Rice", TeamID = 33, Age = 24, Height = "6-4", Position = "G" },
                        new Player { Name = "Blake Wesley", TeamID = 33, Age = 20, Height = "6-3", Position = "G" },
                        new Player { Name = "Cedi Osman", TeamID = 33, Age = 28, Height = "6-7", Position = "F" },
                        new Player { Name = "Doug McDermott", TeamID = 33, Age = 31, Height = "6-6", Position = "F" },
                        new Player { Name = "Malaki Branham", TeamID = 33, Age = 20, Height = "6-4", Position = "F" },
                        new Player { Name = "Zach Collins", TeamID = 33, Age = 26, Height = "6-11", Position = "F-C" },
                        new Player { Name = "Devin Vassell", TeamID = 33, Age = 23, Height = "6-5", Position = "G-F" },
                        new Player { Name = "Sidy Cissoko", TeamID = 33, Age = 19, Height = "6-6", Position = "G" },
                        new Player { Name = "Dominick Barlow", TeamID = 33, Age = 20, Height = "6-9", Position = "F" },
                        new Player { Name = "Charles Bediako", TeamID = 33, Age = 21, Height = "7-0", Position = "C" },
                        new Player { Name = "Charles Bassey", TeamID = 33, Age = 23, Height = "6-10", Position = "C-F" },
                        new Player { Name = "Julian Champagnie", TeamID = 33, Age = 22, Height = "6-7", Position = "F" },
                        new Player { Name = "Tre Jones", TeamID = 33, Age = 23, Height = "6-1", Position = "G" },
                        new Player { Name = "Sandro Mamukelashvili", TeamID = 33, Age = 24, Height = "6-9", Position = "F-C" },








                        new Player { Name = "Michael Jordan", Age = 59, Height = "6-6", Position = "G-F" },
                        new Player { Name = "Dennis Rodman", Age = 60, Height = "6-7", Position = "F" },
                        new Player { Name = "Scottie Pippen", Age = 56, Height = "6-7", Position = "F" },
                        new Player { Name = "Horace Grant", Age = 57, Height = "6-10", Position = "F" },
                        new Player { Name = "Jhon Paxson", Age = 62, Height = "6-2", Position = "G" },
                        new Player { Name = "Kobe Bryant", Age = 41, Height = "6-6", Position = "G" }, // Horace Grant był w Lakersach wtedy
                        new Player { Name = "Shaquille O'Neal", Age = 50, Height = "7-1", Position = "C" },
                        new Player { Name = "Derek Fisher", Age = 48, Height = "6-1", Position = "G" },
                        new Player { Name = "Ron Harper", Age = 59, Height = "6-6", Position = "G" },
                        new Player { Name = "Magic Johnson", Age = 62, Height = "6-9", Position = "G" },
                        new Player { Name = "Kareem Abdul-Jabbar", Age = 75, Height = "7-2", Position = "C" },
                        new Player { Name = "James Worthy", Age = 60, Height = "6-9", Position = "F" },
                        new Player { Name = "Michael Cooper", Age = 60, Height = "6-7", Position = "G" },
                        new Player { Name = "Larry Bird", Age = 65, Height = "6-9", Position = "F" },
                        new Player { Name = "Kevin McHale", Age = 64, Height = "6-10", Position = "F-C" },
                        new Player { Name = "Bill Walton", Age = 69, Height = "6-11", Position = "C" },
                        new Player { Name = "Robert Parish", Age = 68, Height = "7-1", Position = "C" },
                        new Player { Name = "Tim Duncan", Age = 45, Height = "6-11", Position = "F-C" },
                        new Player { Name = "Tony Parker", Age = 41, Height = "6-2", Position = "G" },
                        new Player { Name = "Manu Ginobili", Age = 45, Height = "6-6", Position = "G" },
                        new Player { Name = "Boris Diaw", Age = 41, Height = "6-8", Position = "F" },
                        new Player { Name = "Hakeem Olajuwon", Age = 59, Height = "7-0", Position = "C" },
                        new Player { Name = "Kenny Smith", Age = 58, Height = "6-3", Position = "G" },
                        new Player { Name = "Sam Cassell", Age = 54, Height = "6-3", Position = "G" },
                        new Player { Name = "Robert Horry", Age = 53, Height = "6-8", Position = "F" },
                        new Player { Name = "Bill Russell", Age = 88, Height = "6-9", Position = "C" },
                        new Player { Name = "Sam Jones", Age = 88, Height = "6-4", Position = "G" },
                        new Player { Name = "John Havlicek", Age = 79, Height = "6-5", Position = "F-G" },
                        new Player { Name = "Tom Sanders", Age = 82, Height = "6-6", Position = "F" },
                        new Player { Name = "Tom Heinsohn", Age = 87, Height = "6-7", Position = "F" },
                        new Player { Name = "Oscar Robertson", Age = 83, Height = "6-5", Position = "G" },
                        new Player { Name = "Jerry West", Age = 83, Height = "6-3", Position = "G" },
                        new Player { Name = "Elgin Baylor", Age = 86, Height = "6-5", Position = "F" },
                        new Player { Name = "Wilt Chamberlain", Age = 63, Height = "7-1", Position = "C" },
                        new Player { Name = "Karl Malone", Age = 58, Height = "6-9", Position = "F" },
                        new Player { Name = "John Stockton", Age = 60, Height = "6-1", Position = "G" },
                        new Player { Name = "Bryon Russell", Age = 52, Height = "6-7", Position = "F-G" },
                        new Player { Name = "Isiah Thomas", Age = 60, Height = "6-1", Position = "G" }, // Rodman był w  88 Pistons
                        new Player { Name = "Bill Laimbeer", Age = 65, Height = "6-11", Position = "C" },
                        new Player { Name = "Mark Aguirre", Age = 61, Height = "6-6", Position = "F" },
                        new Player { Name = "Joe Dumars", Age = 59, Height = "6-3", Position = "G" },
                        new Player { Name = "David Robinson", Age = 56, Height = "7-1", Position = "C" },
                        new Player { Name = "Dirk Nowitzki", Age = 43, Height = "7-0", Position = "F" },
                        new Player { Name = "Jason Kidd", Age = 50, Height = "6-4", Position = "G" },
                        new Player { Name = "Jason Terry", Age = 46, Height = "6-2", Position = "G" },
                        new Player { Name = "Tyson Chandler", Age = 40, Height = "7-0", Position = "C" },
                        new Player { Name = "Dwyane Wade", Age = 39, Height = "6-4", Position = "G" },
                        new Player { Name = "Ray Allen", Age = 46, Height = "6-5", Position = "G" },
                        new Player { Name = "Chris Bosh", Age = 39, Height = "6-11", Position = "C" },
                        new Player { Name = "Mario Chalmers", Age = 37, Height = "6-2", Position = "G" },
                        new Player { Name = "Charles Barkley", Age = 59, Height = "6-6", Position = "F" },
                        new Player { Name = "Allen Iverson", Age = 46, Height = "6-0", Position = "G" },
                        new Player { Name = "Patrick Ewing", Age = 60, Height = "7-0", Position = "C" },
                        new Player { Name = "Clyde Drexler", Age = 59, Height = "6-7", Position = "G-F" },
                        new Player { Name = "George Gervin", Age = 69, Height = "6-7", Position = "G-F" },
                        new Player { Name = "Bob Cousy", Age = 93, Height = "6-1", Position = "G" },
                        new Player { Name = "George Mikan", Age = 80, Height = "6-10", Position = "C" },
                        new Player { Name = "Bob Pettit", Age = 89, Height = "6-9", Position = "F-C" },
                        new Player { Name = "Dave Cowens", Age = 73, Height = "6-9", Position = "F-C" },
                        new Player { Name = "Gary Payton", Age = 54, Height = "6-3", Position = "G" },
                        new Player { Name = "Dikembe Mutombo", Age = 55, Height = "7-2", Position = "C" },
                        new Player { Name = "Chris Webber", Age = 49, Height = "6-9", Position = "F-C" },
                        new Player { Name = "Steve Nash", Age = 48, Height = "6-3", Position = "G" },
                        new Player { Name = "Allen Houston", Age = 50, Height = "6-6", Position = "G" },
                        new Player { Name = "Manu Ginobili", Age = 44, Height = "6-6", Position = "G" },
                        new Player { Name = "Shawn Kemp", Age = 52, Height = "6-10", Position = "F-C" },
                        new Player { Name = "Vince Carter", Age = 45, Height = "6-6", Position = "F-G" },
                        new Player { Name = "Gilbert Arenas", Age = 40, Height = "6-3", Position = "G" },
                        new Player { Name = "Alonzo Mourning", Age = 51, Height = "6-10", Position = "C" },
                        new Player { Name = "Moses Malone", Age = 60, Height = "6-10", Position = "C" },
                        new Player { Name = "Julius Erving", Age = 73, Height = "6-7", Position = "F" },
                        new Player { Name = "Maurice Cheeks", Age = 67, Height = "6-1", Position = "G" },
                        new Player { Name = "Bobby Jones", Age = 72, Height = "6-9", Position = "F" },
                        new Player { Name = "Billy Cunningham", Age = 78, Height = "6-6", Position = "F" },
                        new Player { Name = "Earl Monroe", Age = 77, Height = "6-3", Position = "G" },
                        new Player { Name = "Bob McAdoo", Age = 70, Height = "6-9", Position = "F-C" },
                        new Player { Name = "Nate Thurmond", Age = 74, Height = "6-11", Position = "F-C" },
                        new Player { Name = "Artis Gilmore", Age = 72, Height = "7-2", Position = "C" },
                        new Player { Name = "Neil Johnston", Age = 81, Height = "6-8", Position = "F-C" },
                        new Player { Name = "Lenny Wilkens", Age = 84, Height = "6-1", Position = "G" },
                        new Player { Name = "George Yardley", Age = 75, Height = "6-5", Position = "F" },
                        new Player { Name = "Wes Unseld", Age = 74, Height = "6-7", Position = "C-F" },
                        new Player { Name = "Paul Arizin", Age = 78, Height = "6-4", Position = "F-G" },
                        new Player { Name = "Elvin Hayes", Age = 75, Height = "6-9", Position = "F-C" },
                        new Player { Name = "Clyde Lovellette", Age = 86, Height = "6-9", Position = "F-C" },
                        new Player { Name = "Joe Dumars", Age = 59, Height = "6-3", Position = "G" },
                        new Player { Name = "Rick Barry", Age = 78, Height = "6-7", Position = "F" },
                        new Player { Name = "Hal Greer", Age = 81, Height = "6-2", Position = "G" },
                        new Player { Name = "Robert Pettit", Age = 89, Height = "6-9", Position = "F-C" },
                        new Player { Name = "Dave Cowens", Age = 73, Height = "6-9", Position = "F-C" },
                        new Player { Name = "Walt Frazier", Age = 76, Height = "6-4", Position = "G" },
                        new Player { Name = "Willis Reed", Age = 79, Height = "6-9", Position = "C-F" },
                        new Player { Name = "Dave DeBusschere", Age = 62, Height = "6-6", Position = "F" },
                        new Player { Name = "Paul Pierce", Age = 44, Height = "6-6", Position = "F" },
                        new Player { Name = "Kevin Garnett", Age = 45, Height = "6-11", Position = "F-C" },
                        new Player { Name = "Tony Allen", Age = 40, Height = "6-4", Position = "G" },
                        new Player { Name = "Rajon Rondo", Age = 37, Height = "6-1", Position = "G" },
                        new Player { Name = "Tracy McGrady", Age = 43, Height = "6-8", Position = "F" },
                        new Player { Name = "Reggie Miller", Age = 57, Height = "6-7", Position = "G-F" },
                        new Player { Name = "Yao Ming", Age = 41, Height = "7-6", Position = "C" },
                        new Player { Name = "Grant Hill", Age = 49, Height = "6-8", Position = "F" },
                        new Player { Name = "J.R Smith", Age = 38, Height = "6-6", Position = "G" },
                        new Player { Name = "Richard Jefferson", Age = 42, Height = "6-97", Position = "F" },
                        new Player { Name = "Ben Wallace", Age = 49, Height = "6-9", Position = "C" },
                        new Player { Name = "Chauncey Billups", Age = 45, Height = "6-3", Position = "G" },
                        new Player { Name = "Rasheed Wallace", Age = 49, Height = "6-11", Position = "F-C" },
                        new Player { Name = "Tayshaun Prince", Age = 43, Height = "6-9", Position = "F" },
                        new Player { Name = "Maurice Lucas", Age = 71, Height = "6-9", Position = "F" },
                        new Player { Name = "Lionel Hollins", Age = 71, Height = "6-3", Position = "G" },
                        new Player { Name = "Bob Gross", Age = 71, Height = "6-6", Position = "F" },
                        new Player { Name = "Pau Gasol", Age = 43, Height = "7-0", Position = "C" },
                        new Player { Name = "Lamar Odom", Age = 44, Height = "6-10", Position = "F" },
                        new Player { Name = "Trevor Ariza", Age = 39, Height = "6-8", Position = "F" },
                        new Player { Name = "Andre Iguodala", Age = 39, Height = "6-6", Position = "F" },




                    };
                    _dbContext.Players.AddRange(playersData);
                    await _dbContext.SaveChangesAsync();
                }
            }
        }
    }
}
